### ISSUE TITLE
Healthbar stuck at around 95%

### ISSUE THREAD

**Issue by geekfoxx** [AzerPUG/Timed-Enouncters#11]
After working with Timed Encounters a few times now the Dynamic Healtbar is hardstuck at around 95% permanently. Even when manually deactivating the Addon and reactivating it the error still persists.

**Comment by Arco-Dielhof** [comment]
@geekfoxx please be so kind to download the following two AddOns, they will show a lot more info if you get an error that _**might**_ be causing this.

[BugGrabber](https://www.curseforge.com/wow/addons/bug-grabber)  
[BugSack](https://www.curseforge.com/wow/addons/bugsack)  

Both AddOns work out of the box and just collect your errors. Once you have them, after combat (assumung it happened again) you can open the interface through the minimap button and copy-paste the error info in here in a comment.

That will probably speed me up about a week of testing/reproducing the error 😋
